### ISSUE TITLE
3.0.13  does not build on Linux 2.2 14

### ISSUE THREAD

**Issue by memmerto** [MarcNo/lifelines#73]
did the following:

./configure --prefix=/opt/lifelines
make

and ended up with this result:

gcc  -g -O2 -W -Wall -Wcast-align
-Wmissing-declarations -Wmissing-prototypes
-Wreturn-type -Wstrict-prototypes -pedantic -g  -o
llines  add.o advedit.o ask.o askprogram.o browse.o
delete.o edit.o error.o export.o import.o lbrowse.o
main.o menuitem.o merge.o miscutls.o newrecs.o
pedigree.o scan.o show.o screen.o swap.o tandem.o
valgdcom.o ../interp/libinterp.a
../gedlib/libgedcom.a        ../btree/libbtree.a
../stdlib/libstdlib.a ../arch/libarch.a      -lncurses
../gedlib/libgedcom.a\(init.o\): In function
\`init\_lifelines\_global':
/\_o/opt.dir/pkg/lifelines-3.0.13/src/lifelines-3.0.13/gedlib/init.c:97:
undefined reference to \`bind\_textdomain\_codeset'
collect2: ld returned 1 exit status
make\[2\]: \*\*\* \[llines\] Error 1
make\[2\]: Leaving directory
\`/opt/lifelines-3.0.13/src/lifelines-3.0.13/liflines'

Reported by: *anonymous

Original Ticket: "bugs/74":https://sourceforge.net/p/bugs/74
